# Generated by Django 3.2.9 on 2021-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20211119_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='pictures/noimg.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
