# Generated by Django 3.2.9 on 2021-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20211124_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='admin@admin.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_by',
            field=models.CharField(default='admin@admin.com', max_length=100),
        ),
    ]
