# Generated by Django 3.2.9 on 2021-11-28 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20211124_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='msg_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
